### ISSUE TITLE
CSS - Nav Scroll showing 

### ISSUE THREAD

**Issue by TristonFelix** [fireship-io/222-responsive-icon-nav-css#32]
`.navbar {
  position: fixed;
  background-color: var(--bg-primary);
  transition: width 600ms ease;
  overflow: scroll; 
}`

Change overflow to "hidden"

**Comment by YonLiud** [comment]
just add these lines to your css file
```css
::-webkit-scrollbar {
  width: 0px;
  background: transparent;
}
```
